import type {Metadata} from "next";
import "../../styles/globals.css";
import Header from '../../components/Header';
import Filter from '../../components/Filter';
import "@fortawesome/fontawesome-svg-core/styles.css";
import {config} from "@fortawesome/fontawesome-svg-core";
import {auth} from "@/lib/auth";

config.autoAddCss = false;
import {SessionProvider} from "next-auth/react";
import React from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className="font-poppins bg-mtoko-dark">
        <div className="app-wrapper">
          <SessionProvider>
            <Header/>

            <Filter/>
            {children}
          </SessionProvider>
        </div>
        </body>
        </html>
    );
}
